/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Show Argument Name",
  "description": "Shows the name of function arguments when right-clicking on them in the editor.",
  "tags": [
    "new"
  ],
  "credits": [
    {
      "name": "Cwulaek",
      "link": "https://github.com/Cwulaek"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "settings": [
    {
      "dynamic": true,
      "name": "Delay duration",
      "id": "delay",
      "type": "select",
      "potentialValues": [
        {
          "name": "None",
          "id": "none"
        },
        {
          "name": "Short",
          "id": "short"
        },
        {
          "name": "Long",
          "id": "long"
        }
      ],
      "default": "none"
    },
    {
      "dynamic": true,
      "name": "Follow mouse",
      "id": "follow-mouse",
      "type": "boolean",
      "default": true
    },
    {
      "dynamic": true,
      "name": "Transparency (%)",
      "id": "transparency",
      "type": "integer",
      "min": 0,
      "max": 100,
      "default": 25
    },
    {
      "dynamic": true,
      "name": "Reduce animation",
      "id": "reduce-animation",
      "type": "boolean",
      "default": false
    }
  ],
  "dynamicDisable": true,
  "enabledByDefault": false
};
export default manifest;