/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Dim Empty Cells",
  "description": "Make empty cells in the workspace dimmed.",
  "tags": [
    "new"
  ],
  "credits": [
    {
      "name": "Cwulaek",
      "link": "https://www.github.com/Cwulaek"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "settings": [
    {
      "name": "Dim Color",
      "id": "dim",
      "description": "The color which empty cells dim to.",
      "type": "color",
      "default": "#88888888",
      "allowTransparency": true
    }
  ],
  "dynamicDisable": true,
  "enabledByDefault": false
};
export default manifest;
